/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false functions/worker-configuration.d.ts` (hash: 0487d4a9257981e2940046b1fc69ec98)
interface __BaseEnv_Env {
	DB: D1Database;
	VITE_ENABLE_DEV_LOGIN: string;
	VITE_DEV_USER: string;
	VITE_DEV_PASSWORD: string;
	VITE_API_MODE: string;
}
declare namespace Cloudflare {
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "VITE_ENABLE_DEV_LOGIN" | "VITE_DEV_USER" | "VITE_DEV_PASSWORD" | "VITE_API_MODE">> {}
}
