/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false functions/worker-configuration.d.ts` (hash: ee560da6d5afae460fa4524bda5f01d0)
interface __BaseEnv_Env {
	COLLECTION_R2: R2Bucket;
	DB: D1Database;
}
declare namespace Cloudflare {
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
