/* eslint-disable */
// Generated by Wrangler types; synchronized with the R2 bindings in wrangler.toml.
interface __BaseEnv_Env {
	ARCH_DRAFT_R2: R2Bucket;
	COLLECTION_R2: R2Bucket;
	DB: D1Database;
}
declare namespace Cloudflare {
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
