name = "my-app"
compatibility_date = "2026-08-31"
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "my-app"
migrations_dir = "./migrations"
# Cloudflareで作成したD1 database IDに置き換えてください。
database_id = "ce71b5d2-ac90-47f1-9a88-223c6ac924f2"
